python CareersFuture_search.py  "Data scientist"
python CareersFuture_search.py  "Software Engineer"
python CareersFuture_search.py  "Project Manager"
python CareersFuture_search.py  "Consultant"
python CareersFuture_search.py  "Senior Software Engineer"
python CareersFuture_search.py  "Research Assistant"
python CareersFuture_search.py  "Principal Analyst (Data Analytics)"
python CareersFuture_search.py  "Principal Consultant"
python CareersFuture_search.py  "Product Developer (Analytics)"
python CareersFuture_search.py  "Product Support Engineer"
python CareersFuture_search.py  "Operations Planning Analyst"
python CareersFuture_search.py  "Senior Actuary Actuarial and Risk Management"
python CareersFuture_search.py  "Senior Analyst"
python CareersFuture_search.py  "Senior Associate"
python CareersFuture_search.py  "Senior Business Analyst"
python CareersFuture_search.py  "Senior Consultant"
python CareersFuture_search.py  "Senior Engineer"
python CareersFuture_search.py  "Senior Data Analyst"
python CareersFuture_search.py  "Senior Data Architect"
python CareersFuture_search.py  "IT Consultant"
python CareersFuture_search.py  "Senior Fraud Engineer"
python CareersFuture_search.py  "Senior Manager / Architect"
python CareersFuture_search.py  "Senior Security Engineer"
python CareersFuture_search.py  "Senior Statistical Analyst"
python CareersFuture_search.py  "Senior System Analyst"
python CareersFuture_search.py  "Senior Systems Engineer"
python CareersFuture_search.py  "Sr' Project Manager (SkillsFuture Singapore)"
python CareersFuture_search.py  "Strategic Policy & Planning Manager"
python CareersFuture_search.py  "Vice President IT"
python CareersFuture_search.py  "Web Hosting Manager"
python CareersFuture_search.py  "Workflow and BPM Product Manager"
python CareersFuture_search.py  "Data Science (Data Innovation Lab)"
python CareersFuture_search.py  "Apprentice"
python CareersFuture_search.py  "Assistant Manager"
python CareersFuture_search.py  "Associate"
python CareersFuture_search.py  "Asst Principal Engineer"
python CareersFuture_search.py  "Business Analyst"
python CareersFuture_search.py  "Business Analytics Analyst"
python CareersFuture_search.py  "Business Analytics Developer"
python CareersFuture_search.py  "Consulting Manager"
python CareersFuture_search.py  "Contract Predictive Analyst"
python CareersFuture_search.py  "Data & Analytics - Senior Consultant"
python CareersFuture_search.py  "Data Analyst - Pricing Analytics"
python CareersFuture_search.py  "Data Analyst (consumer analysis part-time)"
python CareersFuture_search.py  "Data Migration Manager"
python CareersFuture_search.py  "Data Quality Consultant"
python CareersFuture_search.py  "MTS (Member of Technical Staff) YMS"
python CareersFuture_search.py  "Data Science Analyst"
python CareersFuture_search.py  "Data Scientist - Advanced Analytics"
python CareersFuture_search.py  "Deputy Head of Department"
python CareersFuture_search.py  "Development Manager"
python CareersFuture_search.py  "Director Global Research Services"
python CareersFuture_search.py  "Enterprise Data Architect|Enterprise Architect Office"
python CareersFuture_search.py  "Entrepreneur"
python CareersFuture_search.py  "Executive"
python CareersFuture_search.py  "Functional Consultant"
python CareersFuture_search.py  "Global Data Analyst"
python CareersFuture_search.py  "Graduate Research Assistant"
python CareersFuture_search.py  "IT Analyst"
python CareersFuture_search.py  "Ad Hoc Trainer"
python CareersFuture_search.py  "Member of Technical Staff (MTS) - IT"
